"""added_new_columns_title_description

Revision ID: 501c8dac501d
Revises: 0cc9e1ff9c19
Create Date: 2026-02-04 13:43:27.906688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '501c8dac501d'
down_revision: Union[str, Sequence[str], None] = '0cc9e1ff9c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('title', sa.String(), nullable=True))
    op.add_column('time_entries', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_entries', 'title')
    op.drop_column('time_entries', 'description')
    # ### end Alembic commands ###
