"""delete unused columns

Revision ID: e465ecbe595f
Revises: b7275ffb6e4c
Create Date: 2026-01-07 16:16:27.185759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e465ecbe595f'
down_revision: Union[str, Sequence[str], None] = 'b7275ffb6e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_icloud_email_key'), 'users', type_='unique')
    op.drop_column('users', 'icloud_email')
    op.drop_column('users', 'app_specific_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('app_specific_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('icloud_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_icloud_email_key'), 'users', ['icloud_email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
